"""Public pages: the landing page, the API page, the explorer, and one hash's detail.

`/`             — the landing page: the pitch to a tool maintainer, the numbers, the map.
`/api`          — the API page, as opposed to the schema at `/docs`.
`/map`          — the explorer: every recording as a point, clickable since `ADR-0012`.
`/browse/<hash>` — direct lookup of a specific fingerprint (paste-friendly for developers).
`/browse/hash/<prefix>`, `/browse/recent` — the JSON the explorer reads.
"""

import json
import re
from pathlib import Path

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from sqlalchemy import func, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import DbSession
from app.api.routes import _recordings_for
from app.cache import stats_cache
from app.config import settings
from app.db.models import AnalysisDetail, Embedding, Features, RecordingClaim
from app.limiter import limiter
from app.templates import fmt_vec_preview, templates

browse_router = APIRouter(tags=["browse"])

HEX_RE = re.compile(r"^[0-9a-fA-F]+$")

#: `ADR-0002`'s similarity endpoint, HNSW over the whole corpus, measured at about
#: 3 ms when it shipped and restated in `ADR-0012`'s Implementation block on
#: 2026-09-13. A constant rather than a live measurement, so it carries its date
#: onto the page — a figure without one is indistinguishable from a wrong one.
SIMILARITY_MS = 3
SIMILARITY_MEASURED = "2026-09"

MAP_JSON = Path(__file__).resolve().parents[1] / "static" / "map.json"


def _map_meta() -> dict:
    """What the committed projection says about itself, for the caption.

    Read once at import: the file is a release-like artifact regenerated by
    `scripts/build_map.py`, and the caption must carry *its* date and count, not
    the corpus's — the picture and the numbers can honestly disagree by weeks.
    """
    try:
        with MAP_JSON.open() as fh:
            d = json.load(fh)
    except (OSError, ValueError):
        return {"generated": None, "count": 0, "pipeline_version": None, "available": False}
    return {
        "generated": d.get("generated"),
        "count": int(d.get("count") or 0),
        "pipeline_version": d.get("pipeline_version"),
        "available": True,
    }


MAP_META = _map_meta()


# ---------- aggregation helpers (each cached separately under stats_cache) ----------


async def _fetch_counts(db: AsyncSession) -> dict:
    """Row counts for the API page. Cheap aggregates, not the landing page's full set."""
    embeddings = await db.scalar(select(func.count()).select_from(Embedding))
    features = await db.scalar(select(func.count()).select_from(Features))
    # Rows anyone has named, `ADR-0012`: the coverage number that says whether a
    # similarity result will resolve. Distinct hashes, not claims — two clients
    # naming one row is one named row.
    named = await db.scalar(select(func.count(func.distinct(RecordingClaim.fingerprint_hash))))
    return {"embeddings": embeddings or 0, "features": features or 0, "named": named or 0}


async def _fetch_top_stats(db: AsyncSession) -> dict:
    """The four numbers a maintainer weighs: how much is here, how much of it a
    person can read, how fast it answers, and how many are already in.

    The last one is the honest one. The site's voice has always been "almost every
    vector here came from one library", and a page that says so on the first
    screen is a page a maintainer trusts. `client_id` is null on rows contributed
    before 2026-09-04 (`ADR-0004`), so this counts installations that have
    identified themselves, which is what a second contributor would be.
    """
    embeddings = await db.scalar(select(func.count()).select_from(Embedding)) or 0
    named = await db.scalar(select(func.count(func.distinct(RecordingClaim.fingerprint_hash)))) or 0
    contributors = (
        await db.scalar(
            select(func.count(func.distinct(Embedding.client_id))).where(Embedding.client_id.is_not(None))
        )
        or 0
    )
    return {
        "embeddings": int(embeddings),
        "named": int(named),
        "named_pct": (named / embeddings) if embeddings else 0.0,
        "contributors": int(contributors),
    }


async def _fetch_velocity(db: AsyncSession) -> dict:
    last_24h = (await db.execute(
        select(func.count()).select_from(Embedding)
        .where(Embedding.created_at > func.now() - text("interval '24 hours'"))
    )).scalar() or 0
    last_7d = (await db.execute(
        select(func.count()).select_from(Embedding)
        .where(Embedding.created_at > func.now() - text("interval '7 days'"))
    )).scalar() or 0
    return {"last_24h": int(last_24h), "last_7d": int(last_7d)}


async def _fetch_growth(db: AsyncSession) -> list[dict]:
    """Daily-bucketed cumulative count for the last 90 days, of the rows that exist
    now. Rows removed by migration `011` or `ADR-0010`'s collapse are not here, so
    the line is "what is here, by when it arrived" rather than a history."""
    rows = (await db.execute(text("""
        SELECT day, sum(daily_count) OVER (ORDER BY day) AS cumulative
        FROM (
            SELECT date_trunc('day', created_at) AS day, count(*) AS daily_count
            FROM embeddings
            WHERE created_at > now() - interval '90 days'
            GROUP BY 1
        ) t
        ORDER BY day
    """))).all()
    return [{"day": r.day.date().isoformat(), "cumulative": int(r.cumulative)} for r in rows]


def growth_points(growth: list[dict], width: int = 560, height: int = 140, pad: int = 20) -> str:
    """The growth series as an SVG `points` attribute, so the landing page draws it
    inline with no charting library and no script. One polyline over at most 90
    points; the y range is the series' own so the line fills the box."""
    if not growth:
        return ""
    ys = [g["cumulative"] for g in growth]
    lo, hi = 0, max(ys) or 1
    n = len(growth)
    out = []
    for i, y in enumerate(ys):
        x = 0 if n == 1 else i * width / (n - 1)
        py = height - pad - (y - lo) / (hi - lo) * (height - 2 * pad) if hi > lo else height - pad
        out.append(f"{x:.1f},{py:.1f}")
    return " ".join(out)


# ---------- routes ----------


@browse_router.get("/", response_class=HTMLResponse)
@limiter.limit(settings.lookup_rate_limit)
async def index(request: Request, db: DbSession) -> HTMLResponse:
    """The landing page: the pitch, the numbers, the map, dated."""
    top = await stats_cache.get_or_compute("top_stats", lambda: _fetch_top_stats(db))
    velocity = await stats_cache.get_or_compute("velocity", lambda: _fetch_velocity(db))
    growth = await stats_cache.get_or_compute("growth", lambda: _fetch_growth(db))

    return templates.TemplateResponse(
        request,
        "index.html",
        {
            "top": top,
            "velocity": velocity,
            "growth": growth,
            "growth_points": growth_points(growth),
            "growth_max": max((g["cumulative"] for g in growth), default=0),
            "similarity_ms": SIMILARITY_MS,
            "similarity_measured": SIMILARITY_MEASURED,
            "map_meta": MAP_META,
        },
    )


@browse_router.get("/api", response_class=HTMLResponse)
async def api_page(request: Request, db: DbSession) -> HTMLResponse:
    """The page a developer lands on, as opposed to the schema at `/docs`.

    `/docs` answers "what are the fields"; nobody arrives with that question. They
    arrive asking what this is, whether it costs anything, and what to do when the
    corpus does not have their track — which is the question the published package
    answers and the schema cannot.
    """
    counts = await _fetch_counts(db)
    return templates.TemplateResponse(
        request,
        "api.html",
        {
            "counts": counts,
            "host": request.url.hostname or "clapback.seethroughlab.com",
            "lookup_limit": settings.lookup_rate_limit.replace("/", " per "),
            "contribute_limit": settings.contribute_rate_limit.replace("/", " per "),
        },
    )


@browse_router.get("/map", response_class=HTMLResponse)
async def map_page(request: Request) -> HTMLResponse:
    """The explorer: the corpus as a picture, and since `ADR-0012` as a thing to click.

    Serves a template and a static artifact; the projection itself is computed
    offline by `scripts/build_map.py`, because UMAP's dependencies have no
    business on an instance sized for a vector index (`ADR-0001` point 3). What
    a click resolves to comes from the two JSON routes below; what it is *called*
    is fetched by the visitor's browser from MusicBrainz, so this server keeps
    `ADR-0012`'s rule of never resolving an id.
    """
    return templates.TemplateResponse(request, "map.html", {"map_meta": MAP_META})


class HashResolution(BaseModel):
    """What one point on the map is, once the visitor asks."""

    fingerprint_hash: str
    pipeline_version: str
    contributor_count: int
    recording_mbid: str | None
    recording_claims: int


class RecentRow(BaseModel):
    fingerprint_hash: str
    created_at: str
    recording_mbid: str | None
    recording_claims: int


class RecentResponse(BaseModel):
    rows: list[RecentRow]


@browse_router.get("/browse/recent", response_model=RecentResponse)
@limiter.limit(settings.lookup_rate_limit)
async def recent(request: Request, db: DbSession, limit: int = 20) -> RecentResponse:
    """The latest contributions, newest first, with the recording each resolves to.

    The list half of browsing: a person with nothing to paste sees what arrived
    most recently and can click into any of it. Names are the visitor's browser's
    business, as everywhere on this site.
    """
    limit = max(1, min(limit, 100))
    rows = (
        await db.execute(
            select(Embedding.fingerprint_hash, Embedding.created_at)
            .order_by(Embedding.created_at.desc())
            .limit(limit)
        )
    ).all()
    recordings = await _recordings_for(db, [r.fingerprint_hash for r in rows])
    return RecentResponse(
        rows=[
            RecentRow(
                fingerprint_hash=r.fingerprint_hash,
                created_at=r.created_at.isoformat(timespec="minutes") if r.created_at else "",
                recording_mbid=recordings[r.fingerprint_hash][0] if r.fingerprint_hash in recordings else None,
                recording_claims=recordings[r.fingerprint_hash][1] if r.fingerprint_hash in recordings else 0,
            )
            for r in rows
        ]
    )


@browse_router.get("/browse/{fingerprint_hash}", response_class=HTMLResponse)
@limiter.limit(settings.lookup_rate_limit)
async def detail(
    request: Request,
    fingerprint_hash: str,
    db: DbSession,
) -> HTMLResponse:
    """Detail view for a single fingerprint: all embeddings, features, and analysis detail."""
    if len(fingerprint_hash) != 64 or not HEX_RE.match(fingerprint_hash):
        raise HTTPException(status_code=422, detail="Invalid fingerprint hash")

    fp = fingerprint_hash.lower()

    embeddings = (await db.execute(
        select(Embedding)
        .where(Embedding.fingerprint_hash == fp)
        .order_by(Embedding.analysis_version.desc(), Embedding.clap_model_version)
    )).scalars().all()

    if not embeddings:
        raise HTTPException(status_code=404, detail="Fingerprint not found")

    features = (await db.execute(
        select(Features)
        .where(Features.fingerprint_hash == fp)
        .order_by(Features.analysis_version.desc())
    )).scalars().all()

    details = (await db.execute(
        select(AnalysisDetail)
        .where(AnalysisDetail.fingerprint_hash == fp)
        .order_by(AnalysisDetail.analysis_version.desc())
    )).scalars().all()

    feat_by_av = {f.analysis_version: f for f in features}
    detail_by_av = {d.analysis_version: d for d in details}

    embeddings_by_av: dict[int, list[Embedding]] = {}
    for e in embeddings:
        embeddings_by_av.setdefault(e.analysis_version, []).append(e)

    versions = []
    for av in sorted(embeddings_by_av.keys(), reverse=True):
        emb_views = []
        for e in embeddings_by_av[av]:
            vec = [float(x) for x in e.embedding] if e.embedding is not None else []
            emb_views.append({
                "clap_model_version": e.clap_model_version,
                # Null on every row contributed before `ADR-0006` phase 2, which
                # is the whole corpus today. The template says so rather than
                # omitting the line, because "not recorded" is the interesting
                # fact about these rows.
                "pipeline_version": e.pipeline_version,
                "contributor_count": e.contributor_count,
                "dims": len(vec),
                "preview": fmt_vec_preview(vec),
                "vec_json": json.dumps(vec),
                "created_at": e.created_at,
                "last_accessed_at": e.last_accessed_at,
            })

        feat = feat_by_av.get(av)
        det = detail_by_av.get(av)
        det_json = json.dumps(det.detail, indent=2, sort_keys=True) if det else None
        versions.append({
            "av": av,
            "embeddings": emb_views,
            "features": feat,
            "features_json": json.dumps(feat.features, indent=2, sort_keys=True) if feat else None,
            "detail": det,
            "detail_json": det_json,
            "detail_size_kb": (len(det_json) / 1024) if det_json else None,
        })

    return templates.TemplateResponse(
        request,
        "browse_detail.html",
        {
            "fingerprint_hash": fp,
            "totals": {
                "embeddings": len(embeddings),
                "features": len(features),
                "details": len(details),
            },
            "versions": versions,
        },
    )


# ---------- the explorer's JSON ----------


@browse_router.get("/browse/hash/{prefix}", response_model=HashResolution)
@limiter.limit(settings.lookup_rate_limit)
async def resolve_prefix(request: Request, prefix: str, db: DbSession) -> HashResolution:
    """A hash from its prefix — the twelve hex characters the map carries per point.

    Twelve is 48 bits; the corpus is tens of thousands of rows, so a collision is
    a curiosity rather than a risk, and an ambiguous prefix is refused rather than
    guessed at. Returns the most-contributed row for the hash and the recording it
    resolves to, if anyone has claimed one.
    """
    prefix = prefix.lower()
    if len(prefix) < 12 or len(prefix) > 64 or not HEX_RE.match(prefix):
        raise HTTPException(status_code=422, detail="prefix must be 12 to 64 hex characters")
    rows = (
        await db.execute(
            select(Embedding.fingerprint_hash, Embedding.pipeline_version, Embedding.contributor_count)
            .where(Embedding.fingerprint_hash.like(prefix + "%"))
            .order_by(Embedding.contributor_count.desc(), Embedding.pipeline_version)
            .limit(3)
        )
    ).all()
    if not rows:
        raise HTTPException(status_code=404, detail="no recording with that prefix")
    hashes = {r.fingerprint_hash for r in rows}
    if len(hashes) > 1:
        raise HTTPException(status_code=409, detail="prefix is ambiguous; send more of it")
    h, pipeline, count = rows[0]
    recording = (await _recordings_for(db, [h])).get(h)
    return HashResolution(
        fingerprint_hash=h,
        pipeline_version=pipeline,
        contributor_count=int(count or 1),
        recording_mbid=recording[0] if recording else None,
        recording_claims=recording[1] if recording else 0,
    )
